appDev:
  image: 192.168.57.29:5000/books-fe-polymer-dev:v1
  volumes:
    - app:/app
  ports:
    - 8081:3000
nginxDev:
  image: nginx
  volumes:
    - conf/nginx.conf:/etc/nginx/nginx.conf
  ports:
    - 8080:80
booksServiceDev:
  image: 192.168.57.29:5000/books-service:v1
  volumes:
    - /data/tests/db:/data/db
  ports:
      - 8082:8080
